<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Simon’s Notes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./assets/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
<script src="https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js" crossorigin="anonymous"></script>


<link rel="stylesheet" href="style.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Simon’s Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" rel="" target="" aria-current="page">
 <span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Contact</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto tools-wide">
    <a href="https://twitter.com" rel="" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-twitter"></i></a>
    <a href="https://github.com/Simontagbor" rel="" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="https://www.kaggle.com/simontagbor" title="" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label=""><i class="bi bi-kaggle"></i></a>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item quarto-navbar-tools ms-auto-item" href="https://github.com/Simontagbor/BritishAirways-predictive-ML">
            Source Code
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools ms-auto-item" href="https://bugs.com">
            Report a Bug
            </a>
          </li>
      </ul>
    </div>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">



<div class="column-body-outset">
<h1 style="color: #00205b; font-family: 'Georgia';">
Forecasting Demand: Unveiling the Future of Product Sales and Crafting the Optimal Inventory Strategy
</h1>
<p><author style="color: #00205b; font-family: 'Georgia';">By: <a href="https://www./">Simon Tagbor</a></author> <date style="color: #00205b; font-family: 'Georgia';">2024-01-21</date></p>
</div>
<blockquote class="blockquote">
<p>
One of the core focus of downstream supply chain operations involves a key responsibility – the ability to navigate the ever-changing landscape of customer demand. Supply chain professionals have adopted statiscal techqniques that ebable them to infer the demand of products based on historical data. This process is relatively straightforward when dealing with smaller product categories and stable demand patterns. However, challenges arise in larger product categories with constantly shifting consumer demands, posing scalability issues for traditional forecasting methods.
</p>
<p>
The traditional approach involves observing the distribution and variability of historical data from ERP systems, combined with expert intuition. Yet, as businesses grow, reducing guesswork in demand forecasting becomes important. The decisions made in inventory optimization can significantly impact costs.
</p>
<p>
In this notebook, I will guide you through building a demand forecasting model to predict product demand based on historical data. Moreover, I’ll demonstrate how this model can be leveraged for inventory optimization, covering concepts like reorder points, safety stock, and economic order quantity (EOQ).
</p>
<p>
Throughout this project, we will address two key business questions:
</p>
<ol>
<li>
<em>What is the demand forecast for the top selling product in the next 24 months?</em>
</li>
<li>
<em>What is the optimal inventory level for the product?</em>
</li>
</ol>
<p>
Join me on this exploration as we seek answers, and feel free to share your thoughts and feedback on my approach.
</p>
<p>You can find the source code for this project at my <a href="https://github.com/Simontagbor/supply-chain-demand-forecast">github page.</a> You can also find the Jupyter notebook and the dataset on my <a href="https://www.kaggle.com/simontagbor/british-airways-predictive-ml">kaggle page</a>.</p>
</blockquote>
<details>
<summary style="font-weight:bold;">
Click to Read Executive Summary on Research Findings
</summary>
<div style="
    font-size: 1.8vw; 
    color: #333; 
    padding: 1.5vw; 
    margin: 1.7vw 0; 
    border-left: 0.35vw solid #7792f9; 
    line-height: 1.6; 
    position: relative; 
    background: #e9f5ff;">
<h2 class="anchored">
Executive Summary
</h2>
<p>
After building and testing the demand forecasting model, we discovered trends, seasonalities and holiday effects on the top-selling product based on the dataset provided we also found the optimal inventory policy for the top-selling product:
</p>
<ul>
<li>
Given the zero variance observed in the product price, The Demand for the <code>product Card ID 365</code> is expected to remain fairly stable within the next two years with cyclical dips in sales within the third quarter of each year(2015 and 2016). it might be worth looking into these top predictors of demand outcomes to control the dips and ultimately improve sales outcomes
</li>
</ul>
<div style="display: grid; grid-template-columns: auto auto; padding: 10px; background-color: white; width:85%; margin-left: 9%;">
<div style="font-size: 1.5vw; text-align: left;">
<ol type="1">
<li>Pending
</li></ol></div>
<div style="font-size: 1.5vw; text-align: left;">
<ol start="2" type="1">
<li>Pending
</li></ol></div>
<div style="font-size: 1.5vw; text-align: left;">
<ol start="3" type="1">
<li>Pending
</li></ol></div>
<div style="font-size: 1.5vw; text-align: left;">
<ol start="4" type="1">
<li>Pending
</li></ol></div>
<div style="font-size: 1.5vw; text-align: left;">
<ol start="5" type="1">
<li>Pending
</li></ol></div>
<div style="font-size: 1.5vw; text-align: left;">
<ol start="6" type="1">
<li>Pending
</li></ol></div>
<div style="font-size: 1.5vw; text-align: left;">
<ol start="7" type="1">
<li>Pending
</li></ol></div>
<div style="font-size: 1.5vw; text-align: left;">
<ol start="8" type="1">
<li>Pending
</li></ol></div>
<div style="font-size: 1.5vw; text-align: left;">
<ol start="9" type="1">
<li>Pending
</li></ol></div>
<div style="font-size: 1.5vw; text-align: left;">
<ol start="10" type="1">
<li>Pending
</li></ol></div>










</div>
<ul>
<li>
Based on the Economic Order Quantity Model(EOQ) the optimal inventory policy is
</li>
<p>
</p>
</ul>
<h2 class="anchored">
Potential Application of Insights
</h2>
<p>
</p>
<p>
</p>
</div>
</details>
<h2 class="anchored">
Project Outline
</h2>
<p>For this project, I completed the following tasks:</p>
<ul class="task-list">
<li><input type="checkbox" checked="">Performed Exploratory Data Analysis.</li>
<li><input type="checkbox" checked="">Cleaned and Prepared the data for modeling.</li>
<li><input type="checkbox" checked="">Conducted Time Series Modeling With Prophet.</li>
<li><input type="checkbox" checked="">Evaluated the model performance.</li>
<li><input type="checkbox" checked="">Interpret the model results and answer the business questions.</li>
</ul>
<h2 class="anchored">
Problem Statement
</h2>
<p><em>Large product categories and constantly shifting consumer demand patterns introduce a scaling challenge for traditional demand forecasting techniques. There is a need for an approach that reduces the level of guesswork and reduces the avoidable costly outcomes of poor inventory optimizations </em></p>
<h2 class="anchored">
Project Dependencies
</h2>
<div class="cell" data-execution_count="1">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import project libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np <span class="co"># for linear algebra</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math <span class="co"># for math operations </span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns <span class="co"># for plotting</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># handling files</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># data preprocessing</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> LabelEncoder</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Model Building and Fitting</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestClassifier</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> prophet <span class="im">import</span> Prophet</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Model Evaluation and Tuning</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> accuracy_score, classification_report, confusion_matrix</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="co"># visualisation libraries</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt <span class="co"># for plotting</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> squarify <span class="co"># for tree maps</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<h1>
Exploratory Data Analysis
</h1>
<p>
The working <a href="#">dataset</a> contains entries of customer demand information The data contains 53 features (columns)
</p>
<p>
To understand the data, I performed exploratory data analysis. I used the following techniques to understand the data:
</p>
<ul class="task-list">
<li><input type="checkbox" checked="">Visual inspection of data.</li>
<li><input type="checkbox" checked="">Exploratory Data Visualizations. (Univariate and Bivariate)</li>
</ul>
<h2 class="anchored">
Visual Inspection of Data
</h2>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"data/DataCoSupplyChainDataset.csv"</span>, encoding<span class="op">=</span><span class="st">"ISO-8859-1"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>df.head(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Type</th>
<th data-quarto-table-cell-role="th">Days for shipping (real)</th>
<th data-quarto-table-cell-role="th">Days for shipment (scheduled)</th>
<th data-quarto-table-cell-role="th">Benefit per order</th>
<th data-quarto-table-cell-role="th">Sales per customer</th>
<th data-quarto-table-cell-role="th">Delivery Status</th>
<th data-quarto-table-cell-role="th">Late_delivery_risk</th>
<th data-quarto-table-cell-role="th">Category Id</th>
<th data-quarto-table-cell-role="th">Category Name</th>
<th data-quarto-table-cell-role="th">Customer City</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">Order Zipcode</th>
<th data-quarto-table-cell-role="th">Product Card Id</th>
<th data-quarto-table-cell-role="th">Product Category Id</th>
<th data-quarto-table-cell-role="th">Product Description</th>
<th data-quarto-table-cell-role="th">Product Image</th>
<th data-quarto-table-cell-role="th">Product Name</th>
<th data-quarto-table-cell-role="th">Product Price</th>
<th data-quarto-table-cell-role="th">Product Status</th>
<th data-quarto-table-cell-role="th">shipping date (DateOrders)</th>
<th data-quarto-table-cell-role="th">Shipping Mode</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>DEBIT</td>
<td>3</td>
<td>4</td>
<td>91.250000</td>
<td>314.640015</td>
<td>Advance shipping</td>
<td>0</td>
<td>73</td>
<td>Sporting Goods</td>
<td>Caguas</td>
<td>...</td>
<td>NaN</td>
<td>1360</td>
<td>73</td>
<td>NaN</td>
<td>http://images.acmesports.sports/Smart+watch</td>
<td>Smart watch</td>
<td>327.75</td>
<td>0</td>
<td>2/3/2018 22:56</td>
<td>Standard Class</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>TRANSFER</td>
<td>5</td>
<td>4</td>
<td>-249.089996</td>
<td>311.359985</td>
<td>Late delivery</td>
<td>1</td>
<td>73</td>
<td>Sporting Goods</td>
<td>Caguas</td>
<td>...</td>
<td>NaN</td>
<td>1360</td>
<td>73</td>
<td>NaN</td>
<td>http://images.acmesports.sports/Smart+watch</td>
<td>Smart watch</td>
<td>327.75</td>
<td>0</td>
<td>1/18/2018 12:27</td>
<td>Standard Class</td>
</tr>
</tbody>
</table>

<p>2 rows × 53 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># retrieve the number of columns and rows</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>df.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>(180519, 53)</code></pre>
</div>
</div>
<p>In this truncated output, you can see The data contains 53 features (columns) and 180,519 entries (rows). The data contains a mix of categorical and numerical features.</p>
<p>
You can dive into the details about the description of the dataset <a href="#">here</a>
</p>
<h3 class="anchored">
Initial Data Preprocessing
</h3>
<p>
To Forecast the demand based on the available data, we will focus on historical sales data, and product attributes like; stock level, and product category, we will also analyze the impact of other variables that contribute to demand patterns including geographic factors, customer segments and lead time.
</p>
<h4 class="anchored">
Preprocessing Tasks
</h4>
<ul>
<li>
Drop irrelevant columns
</li>
<li>
Drop rows with missing values
</li>
<li>
Create new features
</li>
<li>
Convert categorical features to numerical features
</li>
</ul>
<p>
Based on the above, we will drop the majority of the columns that are not relevant for forecasting the demand and extract new features from the existing columns
</p>
<h5 class="anchored">
Drop Irrelevant Columns
</h5>
<div class="cell" data-execution_count="15">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># drop irrelevant columns</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> drop_columns(df, columns_to_drop):</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>        df <span class="op">=</span> df.drop(columns<span class="op">=</span>columns_to_drop)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="bu">len</span>(columns_to_drop)<span class="sc">}</span><span class="ss"> columns dropped successfully. Number of columns remaining: </span><span class="sc">{</span><span class="bu">len</span>(df.columns)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> df</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span> <span class="pp">KeyError</span> <span class="im">as</span> e:</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"""Column(s): </span><span class="sc">{</span>e<span class="sc">}</span><span class="ss"> not found in dataframe.</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="ss">              </span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="ss">            No columns dropped.</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="ss">            Please Check that the column names are correct."""</span>)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> df</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify the columns to keep</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>colums_to_keep <span class="op">=</span> [<span class="st">'Days for shipping (real)'</span>, </span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'Customer Country'</span>,</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'Sales per customer'</span>,</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'Delivery Status'</span>, </span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'Late_delivery_risk'</span>, </span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'Customer City'</span>,</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'Customer Segment'</span>,</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'Sales'</span>,<span class="st">'Shipping Mode'</span>,</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'Type'</span>, <span class="st">'Product Card Id'</span>,</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'Customer Zipcode'</span>, </span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'Product Category Id'</span>, </span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'Product Name'</span>,                    </span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'Product Price'</span>,</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'Market'</span>, </span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'Product Status'</span>,</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'shipping date (DateOrders)'</span>,]</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify the columns to drop</span></span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>columns_to_drop <span class="op">=</span> [col <span class="cf">for</span> col <span class="kw">in</span> df.columns <span class="cf">if</span> col <span class="kw">not</span> <span class="kw">in</span> colums_to_keep ]</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> drop_columns(df, columns_to_drop)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>35 columns dropped successfully. Number of columns remaining: 18</code></pre>
</div>
</div>
<h5 class="anchored">
Create New Features
</h5>
<p>The dataset contains a <code>shipping date</code> column which is a <code>DateTime</code> object from which we can extract <code>Month</code>, <code>Year</code>, <code>Day</code> and <code>Day of Week</code> that can be useful in our analysis.</p>
<ul class="task-list">
<li><input type="checkbox" checked=""><code>Month</code> - to capture the months per sale.</li>
<li><input type="checkbox" checked=""><code>Year</code> - to capture the year per sales.</li>
<li><input type="checkbox" checked=""><code>Day</code> - to capture the day per sales.</li>
<li><input type="checkbox" checked=""><code>Day of Week</code> - to capture the day of the week per sales.</li>
</ul>
<p>
I chose <code>Shipping Date</code> over the <code>Order date</code> because it reflects fulfilled demand while the latter captures interest. (the customer could cancel the order)
</p>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create month, Year, Day, and Weekday columns from Shipping Date</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> extract_date_parts(df, date_column, prefix):</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>        df[date_column] <span class="op">=</span> pd.to_datetime(df[date_column])</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>        df[<span class="ss">f'</span><span class="sc">{</span>prefix<span class="sc">}</span><span class="ss"> Year'</span>] <span class="op">=</span> df[date_column].dt.year</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>        df[<span class="ss">f'</span><span class="sc">{</span>prefix<span class="sc">}</span><span class="ss"> Month'</span>] <span class="op">=</span> df[date_column].dt.month</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>        df[<span class="ss">f'</span><span class="sc">{</span>prefix<span class="sc">}</span><span class="ss"> Day'</span>] <span class="op">=</span> df[date_column].dt.day</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>        df[<span class="ss">f'</span><span class="sc">{</span>prefix<span class="sc">}</span><span class="ss"> Weekday'</span>] <span class="op">=</span> df[date_column].dt.weekday</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>        <span class="co"># verify and notify that the columns have been created</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="ss">f'</span><span class="sc">{</span>prefix<span class="sc">}</span><span class="ss"> Year'</span> <span class="kw">in</span> df.columns <span class="kw">and</span> <span class="ss">f'</span><span class="sc">{</span>prefix<span class="sc">}</span><span class="ss"> Month'</span> <span class="kw">in</span> df.columns <span class="kw">and</span> <span class="ss">f'</span><span class="sc">{</span>prefix<span class="sc">}</span><span class="ss"> Day'</span> <span class="kw">in</span> df.columns <span class="kw">and</span> <span class="ss">f'</span><span class="sc">{</span>prefix<span class="sc">}</span><span class="ss"> Weekday'</span> <span class="kw">in</span> df.columns:</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>            <span class="bu">print</span>(<span class="ss">f" Success! Columns Created: </span><span class="sc">{</span>prefix<span class="sc">}</span><span class="ss"> Year, </span><span class="sc">{</span>prefix<span class="sc">}</span><span class="ss"> Month, </span><span class="sc">{</span>prefix<span class="sc">}</span><span class="ss"> Day, and </span><span class="sc">{</span>prefix<span class="sc">}</span><span class="ss"> Weekday"</span>)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> df</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>            <span class="bu">print</span>(<span class="st">"Error creating columns. Please check that the date column name is correct."</span>)</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span> <span class="pp">Exception</span> <span class="im">as</span> e:</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"Error creating columns: </span><span class="sc">{</span>e<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> df</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the function to extract date parts</span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> extract_date_parts(df, <span class="st">'shipping date (DateOrders)'</span>, <span class="st">'Shipping'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Success! Columns Created: Shipping Year, Shipping Month, Shipping Day, and Shipping Weekday</code></pre>
</div>
</div>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<pre><code>(180519, 22)</code></pre>
</div>
</div>
<p>Now we have 22 new columns and 180519 entries (rows) in the dataset.</p>
<h4 class="anchored">
Drop Rows with Missing Values
</h4>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># drop customer Zip code.</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.drop(columns<span class="op">=</span>[<span class="st">'Customer Zipcode'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<h4 class="anchored">
A Quick Spot Check for Missing Values
</h4>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">### Check for Missing values</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>df.isnull().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<pre><code>Type                          0
Days for shipping (real)      0
Sales per customer            0
Delivery Status               0
Late_delivery_risk            0
Customer City                 0
Customer Country              0
Customer Segment              0
Market                        0
Sales                         0
Product Card Id               0
Product Category Id           0
Product Name                  0
Product Price                 0
Product Status                0
shipping date (DateOrders)    0
Shipping Mode                 0
Shipping Year                 0
Shipping Month                0
Shipping Day                  0
Shipping Weekday              0
dtype: int64</code></pre>
</div>
</div>
<p>
There are currently no null values in the dataset. This is good news!
</p>
<p>
To explore the spread of the data, we will use the <code>describe()</code> method to get the summary statistics of the data.
</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>df.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Days for shipping (real)</th>
<th data-quarto-table-cell-role="th">Sales per customer</th>
<th data-quarto-table-cell-role="th">Late_delivery_risk</th>
<th data-quarto-table-cell-role="th">Sales</th>
<th data-quarto-table-cell-role="th">Product Card Id</th>
<th data-quarto-table-cell-role="th">Product Category Id</th>
<th data-quarto-table-cell-role="th">Product Price</th>
<th data-quarto-table-cell-role="th">Product Status</th>
<th data-quarto-table-cell-role="th">shipping date (DateOrders)</th>
<th data-quarto-table-cell-role="th">Shipping Year</th>
<th data-quarto-table-cell-role="th">Shipping Month</th>
<th data-quarto-table-cell-role="th">Shipping Day</th>
<th data-quarto-table-cell-role="th">Shipping Weekday</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>180519.000000</td>
<td>180519.000000</td>
<td>180519.000000</td>
<td>180519.000000</td>
<td>180519.000000</td>
<td>180519.000000</td>
<td>180519.000000</td>
<td>180519.0</td>
<td>180519</td>
<td>180519.000000</td>
<td>180519.000000</td>
<td>180519.000000</td>
<td>180519.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>3.497654</td>
<td>183.107609</td>
<td>0.548291</td>
<td>203.772096</td>
<td>692.509764</td>
<td>31.851451</td>
<td>141.232550</td>
<td>0.0</td>
<td>2016-06-16 05:45:23.202433024</td>
<td>2015.979404</td>
<td>6.252494</td>
<td>15.702170</td>
<td>2.997385</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">min</td>
<td>0.000000</td>
<td>7.490000</td>
<td>0.000000</td>
<td>9.990000</td>
<td>19.000000</td>
<td>2.000000</td>
<td>9.990000</td>
<td>0.0</td>
<td>2015-01-03 00:00:00</td>
<td>2015.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">25%</td>
<td>2.000000</td>
<td>104.379997</td>
<td>0.000000</td>
<td>119.980003</td>
<td>403.000000</td>
<td>18.000000</td>
<td>50.000000</td>
<td>0.0</td>
<td>2015-09-25 06:59:00</td>
<td>2015.000000</td>
<td>3.000000</td>
<td>8.000000</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">50%</td>
<td>3.000000</td>
<td>163.990005</td>
<td>1.000000</td>
<td>199.919998</td>
<td>627.000000</td>
<td>29.000000</td>
<td>59.990002</td>
<td>0.0</td>
<td>2016-06-15 08:32:00</td>
<td>2016.000000</td>
<td>6.000000</td>
<td>16.000000</td>
<td>3.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">75%</td>
<td>5.000000</td>
<td>247.399994</td>
<td>1.000000</td>
<td>299.950012</td>
<td>1004.000000</td>
<td>45.000000</td>
<td>199.990005</td>
<td>0.0</td>
<td>2017-03-04 21:29:00</td>
<td>2017.000000</td>
<td>9.000000</td>
<td>23.000000</td>
<td>5.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">max</td>
<td>6.000000</td>
<td>1939.989990</td>
<td>1.000000</td>
<td>1999.989990</td>
<td>1363.000000</td>
<td>76.000000</td>
<td>1999.989990</td>
<td>0.0</td>
<td>2018-02-06 22:14:00</td>
<td>2018.000000</td>
<td>12.000000</td>
<td>31.000000</td>
<td>6.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">std</td>
<td>1.623722</td>
<td>120.043670</td>
<td>0.497664</td>
<td>132.273077</td>
<td>336.446807</td>
<td>15.640064</td>
<td>139.732492</td>
<td>0.0</td>
<td>NaN</td>
<td>0.831962</td>
<td>3.398391</td>
<td>8.808808</td>
<td>2.002633</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<h4 class="anchored">
Some interesting Highlights from The summary statistics
</h4>
<ol type="1">
<li><p>Aproximately <code>55%</code> of orders had late delivery risks.</p></li>
<li><p>Aproximately <code>75%</code> of products cost <code>$199.99</code></p></li>
<li><p>All the products are available.</p></li>
<li><p>75% of customers bought goods worth at least <code>$247.40</code></p></li>
</ol>
<p>
Further inspection of the data will help us understand the data better.
</p>
<p>
In the next step I will use visualizations to bring to life patterns in the data. These patterns will inform decisions around feature engineering and model selection.
</p>
<h3 class="anchored">
Preprocessing Data for Bivariate Analysis and Machine Learning
</h3>
<p>
</p><p>Some of the variables in the dataset are categorical variables. That presents a challenge because the correlation matrix that will be used for Bivariate analysis requires all variables to have numerical representations.</p>
<p>
For future machine learning modeling, I will need to also separately encode the categorical variables using the <code>OneHotEncoder</code> method from the <code>sklearn</code> library.
</p>
<p>
I wrote a function that returns two preprocessed dataframes: one that is encoded using a label encoder function and the other encoded using one hot encoding technique:
</p>
<p>
You can learn about encoding techniques for categorical variables <a href="#">here</a>
</p>
<p>
The categorical variables in the dataset are:
</p>
<ul>
<li>
<code>Customer Segment</code>
</li>
<li>
<code>Payment Type</code>
</li>
<li>
<code>Delivery Status</code>
</li>
<li>
<code>Category Name</code>
</li>
<li>
<code>Customer Country</code>
</li>
</ul>
<h2 class="anchored">
Exploratory Data Visualizations
</h2>
<p>
To highlight the distributions of the individual variables as well as the relationship between the variables and the target variables, I used the following techniques:
</p>
<ul class="task-list">
<li><input type="checkbox" checked="">Univariate Analysis</li>
<li><input type="checkbox" checked="">Bivariate Analysis</li>
<li><input type="checkbox" checked="">Exploratory Time Series Analysis</li>
</ul>
<h3 class="anchored">
Univariate analysis
</h3>
<p>My goal for this initial step was to understand the overall distribution of each variable in the dataset. I used the following techniques to achieve this:</p>
<ul class="task-list">
<li><input type="checkbox" checked="">distribution plots</li>
<li><input type="checkbox" checked="">tree maps</li>
<li><input type="checkbox" checked="">bar plots</li>
</ul>
<p>Hopefully, patterns and outliers will emerge from this analysis. I will use these insights to inform my decisions around feature selection and model selection.</p>
<div class="cell" data-execution_count="11">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up the grid layout</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(nrows<span class="op">=</span><span class="dv">3</span>, ncols<span class="op">=</span><span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">15</span>))</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">'Distribution Plots for Selected Variables'</span>, </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>             fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a copy of the DataFrame</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>df_copy <span class="op">=</span> df.copy()</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting  the top ten products per Product Card Id</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>sns.countplot(data<span class="op">=</span>df_copy, x<span class="op">=</span><span class="st">'Product Card Id'</span>,</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>                color<span class="op">=</span><span class="st">'blue'</span>, ax<span class="op">=</span>axes[<span class="dv">0</span>, <span class="dv">0</span>], </span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>                order<span class="op">=</span>df_copy[<span class="st">'Product Card Id'</span>].value_counts().iloc[:<span class="dv">10</span>].index)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].set_title(<span class="st">'Distribution of Top Ten Product Id'</span>)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].set_xlabel(<span class="st">'Product Card Id'</span>)</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].set_ylabel(<span class="st">'Count'</span>)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting Value of sales in  dollars</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>sns.histplot(data<span class="op">=</span>df_copy, x<span class="op">=</span><span class="st">'Sales'</span>, </span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>             kde<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span><span class="st">'salmon'</span>, </span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>             bins<span class="op">=</span><span class="dv">30</span>, linewidth<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>             ax<span class="op">=</span>axes[<span class="dv">0</span>, <span class="dv">1</span>])</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].set_title(<span class="st">'Distribution of Sales'</span>)</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].set_xlabel(<span class="st">'Sales value in Dollars'</span>)</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].set_ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting Sales Value per customer</span></span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a>sns.histplot(data<span class="op">=</span>df_copy, x<span class="op">=</span><span class="st">'Sales per customer'</span>,</span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a>             bins<span class="op">=</span><span class="dv">30</span>, kde<span class="op">=</span><span class="va">True</span>, linewidth<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a>             color<span class="op">=</span><span class="st">'lightblue'</span>, ax<span class="op">=</span>axes[<span class="dv">0</span>, <span class="dv">2</span>])</span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">2</span>].set_title(<span class="st">'Distribution of Sales per Customer'</span>)</span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">2</span>].set_xlabel(<span class="st">'Sales per Customer'</span>)</span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">2</span>].set_ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Ploting the distribution of Product Price</span></span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a>sns.histplot(data<span class="op">=</span>df_copy, x<span class="op">=</span><span class="st">'Product Price'</span>, bins<span class="op">=</span><span class="dv">30</span>, kde<span class="op">=</span><span class="va">True</span>, </span>
<span id="cb15-38"><a href="#cb15-38" aria-hidden="true" tabindex="-1"></a>             color<span class="op">=</span><span class="st">'lightgreen'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, ax<span class="op">=</span>axes[<span class="dv">1</span>, <span class="dv">0</span>])</span>
<span id="cb15-39"><a href="#cb15-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-40"><a href="#cb15-40" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].set_title(<span class="st">'Distribution of Product Price'</span>)</span>
<span id="cb15-41"><a href="#cb15-41" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].set_xlabel(<span class="st">'Product Price'</span>)</span>
<span id="cb15-42"><a href="#cb15-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-43"><a href="#cb15-43" aria-hidden="true" tabindex="-1"></a><span class="co"># ploting a tree map for Customer Segment</span></span>
<span id="cb15-44"><a href="#cb15-44" aria-hidden="true" tabindex="-1"></a>squarify.plot(sizes<span class="op">=</span>df_copy[<span class="st">'Customer Segment'</span>].value_counts(), </span>
<span id="cb15-45"><a href="#cb15-45" aria-hidden="true" tabindex="-1"></a>              label<span class="op">=</span>df_copy[<span class="st">'Customer Segment'</span>].value_counts().index, </span>
<span id="cb15-46"><a href="#cb15-46" aria-hidden="true" tabindex="-1"></a>              color<span class="op">=</span>sns.color_palette(<span class="st">"Set3"</span>), ax<span class="op">=</span>axes[<span class="dv">1</span>, <span class="dv">1</span>])</span>
<span id="cb15-47"><a href="#cb15-47" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].set_title(<span class="st">'Distribution of Customer Segment - Treemap'</span>)</span>
<span id="cb15-48"><a href="#cb15-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-49"><a href="#cb15-49" aria-hidden="true" tabindex="-1"></a><span class="co"># ploting a tree map for Top Ten Product Category Id</span></span>
<span id="cb15-50"><a href="#cb15-50" aria-hidden="true" tabindex="-1"></a>squarify.plot(sizes<span class="op">=</span>df_copy[<span class="st">'Product Category Id'</span>].value_counts().iloc[:<span class="dv">10</span>],</span>
<span id="cb15-51"><a href="#cb15-51" aria-hidden="true" tabindex="-1"></a>                label<span class="op">=</span>df_copy[<span class="st">'Product Category Id'</span>].value_counts().iloc[:<span class="dv">10</span>].index,</span>
<span id="cb15-52"><a href="#cb15-52" aria-hidden="true" tabindex="-1"></a>                color<span class="op">=</span>sns.color_palette(<span class="st">"Set2"</span>), ax<span class="op">=</span>axes[<span class="dv">1</span>, <span class="dv">2</span>])</span>
<span id="cb15-53"><a href="#cb15-53" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">2</span>].set_title(<span class="st">'Distribution of Top Ten Product Category Id - Treemap'</span>)</span>
<span id="cb15-54"><a href="#cb15-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-55"><a href="#cb15-55" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the distribution of Delivery Status</span></span>
<span id="cb15-56"><a href="#cb15-56" aria-hidden="true" tabindex="-1"></a>sns.countplot(data<span class="op">=</span>df_copy, x<span class="op">=</span><span class="st">'Delivery Status'</span>,</span>
<span id="cb15-57"><a href="#cb15-57" aria-hidden="true" tabindex="-1"></a>                color<span class="op">=</span><span class="st">'pink'</span>, ax<span class="op">=</span>axes[<span class="dv">2</span>, <span class="dv">0</span>])</span>
<span id="cb15-58"><a href="#cb15-58" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>, <span class="dv">0</span>].set_title(<span class="st">'Distribution of Delivery Status'</span>)</span>
<span id="cb15-59"><a href="#cb15-59" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>, <span class="dv">0</span>].set_xlabel(<span class="st">'Delivery Status'</span>)</span>
<span id="cb15-60"><a href="#cb15-60" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>, <span class="dv">0</span>].set_ylabel(<span class="st">'Count'</span>)</span>
<span id="cb15-61"><a href="#cb15-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-62"><a href="#cb15-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-63"><a href="#cb15-63" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the distribution Payment Type with stacked bar chart</span></span>
<span id="cb15-64"><a href="#cb15-64" aria-hidden="true" tabindex="-1"></a>df_copy.groupby([<span class="st">'Type'</span>])[<span class="st">'Type'</span>].count().plot(kind<span class="op">=</span><span class="st">'bar'</span>, </span>
<span id="cb15-65"><a href="#cb15-65" aria-hidden="true" tabindex="-1"></a>                                               stacked<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb15-66"><a href="#cb15-66" aria-hidden="true" tabindex="-1"></a>                                               ax<span class="op">=</span>axes[<span class="dv">2</span>, <span class="dv">1</span>])</span>
<span id="cb15-67"><a href="#cb15-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-68"><a href="#cb15-68" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>, <span class="dv">1</span>].set_title(<span class="st">'Distribution of Payment Type'</span>)</span>
<span id="cb15-69"><a href="#cb15-69" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>, <span class="dv">1</span>].set_xlabel(<span class="st">'Payment Type'</span>)</span>
<span id="cb15-70"><a href="#cb15-70" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>, <span class="dv">1</span>].set_ylabel(<span class="st">'Count'</span>)</span>
<span id="cb15-71"><a href="#cb15-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-72"><a href="#cb15-72" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the Distribution of top ten Customer Country</span></span>
<span id="cb15-73"><a href="#cb15-73" aria-hidden="true" tabindex="-1"></a>sns.countplot(data<span class="op">=</span>df_copy, x<span class="op">=</span><span class="st">'Customer Country'</span>,</span>
<span id="cb15-74"><a href="#cb15-74" aria-hidden="true" tabindex="-1"></a>                color<span class="op">=</span><span class="st">'orange'</span>, ax<span class="op">=</span>axes[<span class="dv">2</span>, <span class="dv">2</span>], </span>
<span id="cb15-75"><a href="#cb15-75" aria-hidden="true" tabindex="-1"></a>                order<span class="op">=</span>df_copy[<span class="st">'Customer Country'</span>].value_counts().iloc[:<span class="dv">10</span>].index)</span>
<span id="cb15-76"><a href="#cb15-76" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>, <span class="dv">2</span>].set_title(<span class="st">'Distribution of Customer Country'</span>)</span>
<span id="cb15-77"><a href="#cb15-77" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>, <span class="dv">2</span>].set_xlabel(<span class="st">'Customer Country'</span>)</span>
<span id="cb15-78"><a href="#cb15-78" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>, <span class="dv">2</span>].set_ylabel(<span class="st">'Count'</span>)</span>
<span id="cb15-79"><a href="#cb15-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-80"><a href="#cb15-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-81"><a href="#cb15-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-82"><a href="#cb15-82" aria-hidden="true" tabindex="-1"></a><span class="co"># Adjust layout</span></span>
<span id="cb15-83"><a href="#cb15-83" aria-hidden="true" tabindex="-1"></a>plt.tight_layout(rect<span class="op">=</span>[<span class="dv">0</span>, <span class="fl">0.03</span>, <span class="dv">1</span>, <span class="fl">0.95</span>])</span>
<span id="cb15-84"><a href="#cb15-84" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the plots</span></span>
<span id="cb15-85"><a href="#cb15-85" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb15-86"><a href="#cb15-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-87"><a href="#cb15-87" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-11-output-1.png" class="img-fluid"></p>
</div>
</div>
<details>
<summary>
Click to Read My Observations!
</summary>
<p>
The Top Selling <code>Product ID</code> is <code>365</code> which corresponds to a <code>product name</code>: <code>Perfect Fitness Perfect Rip Deck</code> this indicates a fast-moving product. I will focus the demand forecasting process on this product going forward
</p>
<p>
The distribution of <code>Sales Value</code> and <code>Sales per customer</code> are both positively skewed with a long tail. This indicates that the majority of sales are for low-value products. This is an interesting insight because it may suggest that the majority of customers are price-sensitive.
</p>
<p>
The distribution of <code>Product Price</code> is also positively skewed with a long tail. This means that the majority of products are low-value products.
</p>
<p>
The distribution of <code>Customer Segment</code> indicates that the majority of customers are from the consumer segment.
</p>
</details>
<div class="note callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Note:</strong> Based on the insight from the univariate analysis, The rest of the analysis and forecasting will focus on the top selling <code>Product Card Id</code> (<code>365</code> ‘Perfect Fitness Perfect Rip Deck’)</p>
</div>
</div>
</div>
<p>insert image of the top selling product</p>
<div class="cell" data-execution_count="23">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select top selling product</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>top_product <span class="op">=</span> df[<span class="st">'Product Card Id'</span>].value_counts().index[<span class="dv">0</span>]</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co"># get top product ID</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Filtering and Encoding Dataset for Top Product ID: </span><span class="sc">{</span>top_product<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> LabelEncoder</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> prepare_data(df, product_card_id, categorical_cols, columns_to_drop):</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="co">    Prepare a DataFrame for bivariate analysis and machine learning by applying label encoding and one-hot encoding to categorical columns and dropping specified columns.</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a><span class="co">    Parameters:</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="co">    df (pandas.DataFrame): The original DataFrame.</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="co">    product_card_id (int): The product card ID to filter the DataFrame on.</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a><span class="co">    categorical_cols (list of str): The names of the categorical columns to apply encoding to.</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a><span class="co">    columns_to_drop (list of str): The names of the columns to drop from the DataFrame.</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="co">    pandas.DataFrame: The label encoded DataFrame for bivariate analysis.</span></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a><span class="co">    pandas.DataFrame: The one-hot encoded DataFrame for machine learning.</span></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>        df_copy <span class="op">=</span> df[df[<span class="st">'Product Card Id'</span>] <span class="op">==</span> product_card_id].copy()  <span class="co"># create a copy</span></span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>        <span class="co"># label encoding</span></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>        label_encoder <span class="op">=</span> LabelEncoder()</span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>        df_label_encoded <span class="op">=</span> df_copy.copy()</span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Apply label encoding to categorical variables in place</span></span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> col <span class="kw">in</span> categorical_cols:</span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a>            df_label_encoded[col] <span class="op">=</span> label_encoder.fit_transform(df_label_encoded[col])</span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-33"><a href="#cb16-33" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Drop specified columns</span></span>
<span id="cb16-34"><a href="#cb16-34" aria-hidden="true" tabindex="-1"></a>        df_label_encoded <span class="op">=</span> df_label_encoded.drop(columns<span class="op">=</span>columns_to_drop)</span>
<span id="cb16-35"><a href="#cb16-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-36"><a href="#cb16-36" aria-hidden="true" tabindex="-1"></a>        <span class="co"># one-hot encoding</span></span>
<span id="cb16-37"><a href="#cb16-37" aria-hidden="true" tabindex="-1"></a>        df_one_hot_encoded <span class="op">=</span> pd.get_dummies(df_copy, columns<span class="op">=</span>categorical_cols)</span>
<span id="cb16-38"><a href="#cb16-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-39"><a href="#cb16-39" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Drop specified columns</span></span>
<span id="cb16-40"><a href="#cb16-40" aria-hidden="true" tabindex="-1"></a>        df_one_hot_encoded <span class="op">=</span> df_one_hot_encoded.drop(columns<span class="op">=</span>columns_to_drop)</span>
<span id="cb16-41"><a href="#cb16-41" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"Data preparation successful."</span>)</span>
<span id="cb16-42"><a href="#cb16-42" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span>  df_one_hot_encoded, df_label_encoded</span>
<span id="cb16-43"><a href="#cb16-43" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span> <span class="pp">Exception</span> <span class="im">as</span> e:</span>
<span id="cb16-44"><a href="#cb16-44" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"Error preparing data: </span><span class="sc">{</span>e<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb16-45"><a href="#cb16-45" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">None</span>, <span class="va">None</span></span>
<span id="cb16-46"><a href="#cb16-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-47"><a href="#cb16-47" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the function to prepare the data for bivariate analysis</span></span>
<span id="cb16-48"><a href="#cb16-48" aria-hidden="true" tabindex="-1"></a>categorical_cols <span class="op">=</span> [<span class="st">'Type'</span>, <span class="st">'Customer Segment'</span>, </span>
<span id="cb16-49"><a href="#cb16-49" aria-hidden="true" tabindex="-1"></a>                    <span class="st">'Delivery Status'</span>, </span>
<span id="cb16-50"><a href="#cb16-50" aria-hidden="true" tabindex="-1"></a>                    <span class="st">'Customer City'</span>, </span>
<span id="cb16-51"><a href="#cb16-51" aria-hidden="true" tabindex="-1"></a>                    <span class="st">'Market'</span>,</span>
<span id="cb16-52"><a href="#cb16-52" aria-hidden="true" tabindex="-1"></a>                    <span class="st">'Shipping Mode'</span>]</span>
<span id="cb16-53"><a href="#cb16-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-54"><a href="#cb16-54" aria-hidden="true" tabindex="-1"></a>columns_to_drop <span class="op">=</span> [<span class="st">'Product Name'</span>, </span>
<span id="cb16-55"><a href="#cb16-55" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'Customer Country'</span>, </span>
<span id="cb16-56"><a href="#cb16-56" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'shipping date (DateOrders)'</span>, </span>
<span id="cb16-57"><a href="#cb16-57" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'Product Card Id'</span>, </span>
<span id="cb16-58"><a href="#cb16-58" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'Product Category Id'</span>, </span>
<span id="cb16-59"><a href="#cb16-59" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'Product Status'</span>, </span>
<span id="cb16-60"><a href="#cb16-60" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'Product Price'</span>]</span>
<span id="cb16-61"><a href="#cb16-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-62"><a href="#cb16-62" aria-hidden="true" tabindex="-1"></a><span class="co"># drop columns and encode data for correlation martrix and Machine learning</span></span>
<span id="cb16-63"><a href="#cb16-63" aria-hidden="true" tabindex="-1"></a>onehot_encode_df, label_encode_df <span class="op">=</span> prepare_data(df, top_product, categorical_cols, columns_to_drop)</span>
<span id="cb16-64"><a href="#cb16-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-65"><a href="#cb16-65" aria-hidden="true" tabindex="-1"></a><span class="co"># rename Type column to Payment Type</span></span>
<span id="cb16-66"><a href="#cb16-66" aria-hidden="true" tabindex="-1"></a>label_encode_df <span class="op">=</span> label_encode_df.rename(columns<span class="op">=</span>{<span class="st">'Type'</span>: <span class="st">'Payment Type'</span>})</span>
<span id="cb16-67"><a href="#cb16-67" aria-hidden="true" tabindex="-1"></a>onehot_encode_df <span class="op">=</span> onehot_encode_df.rename(columns<span class="op">=</span>{<span class="st">'Type'</span>: <span class="st">'Payment Type'</span>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Filtering and Encoding Dataset for Top Product ID: 365
Data preparation successful.</code></pre>
</div>
</div>
<h5 class="anchored">
Confirm Encoding of Dataset
</h5><h5 class="anchored">
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># validate the data types</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>label_encode_df.dtypes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<pre><code>Payment Type                  int64
Days for shipping (real)      int64
Sales per customer          float64
Delivery Status               int64
Late_delivery_risk            int64
Customer City                 int64
Customer Segment              int64
Market                        int64
Sales                       float64
Shipping Mode                 int64
Shipping Year                 int32
Shipping Month                int32
Shipping Day                  int32
Shipping Weekday              int32
dtype: object</code></pre>
</div>
</div>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>onehot_encode_df.dtypes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<pre><code>Days for shipping (real)          int64
Sales per customer              float64
Late_delivery_risk                int64
Sales                           float64
Shipping Year                     int32
                                 ...   
Market_USCA                        bool
Shipping Mode_First Class          bool
Shipping Mode_Same Day             bool
Shipping Mode_Second Class         bool
Shipping Mode_Standard Class       bool
Length: 590, dtype: object</code></pre>
</div>
</div>
</h5><h3 class="anchored">
Exploratory Time Series Analysis
</h3>
<p>To highlight the trends and seasonality in the sales data, I used the following techniques:</p>
<ul class="task-list">
<li><input type="checkbox" checked="">Time Series Heatmaps</li>
<li><input type="checkbox" checked="">Time Series Modeling with Prophet</li>
</ul>
<h4 class="anchored">
Time Series HeatMap of The Demand(Sales)
</h4>
<p>
To understand the demand patterns over time, I created a heatmap of the demand over time. This will help us understand the cyclical patterns in the demand for the top selling product
</p>
<div class="cell" data-execution_count="65">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> calendar</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co"># extract shipping date (DateOrders) and Sales columns</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>df_heatmap <span class="op">=</span> df[[<span class="st">'shipping date (DateOrders)'</span>, <span class="st">'Sales'</span>]]</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming 'df' is your original dataframe</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="co"># df_heatmap['shipping date (DateOrders)'] = pd.to_datetime(df_heatmap['shipping date (DateOrders)'])  # Convert timestamp to datetime if not already</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>df_heatmap.set_index(<span class="st">'shipping date (DateOrders)'</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>resampled_df <span class="op">=</span> df_heatmap.resample(<span class="st">'M'</span>).<span class="bu">sum</span>()  <span class="co"># Resample to yearly frequency</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Set x-axis ticks to represent months and years</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>month_labels <span class="op">=</span> [calendar.month_abbr[m.month] <span class="op">+</span> <span class="st">'-'</span> <span class="op">+</span> <span class="bu">str</span>(m.year) <span class="cf">for</span> m <span class="kw">in</span> resampled_df.index]</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the heatmap</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">18</span>, <span class="dv">5</span>))</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>sns.heatmap(resampled_df.T, cmap<span class="op">=</span><span class="st">'YlGnBu'</span>, cbar_kws<span class="op">=</span>{<span class="st">'label'</span>: <span class="st">'Sales'</span>})</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>plt.xticks(ticks<span class="op">=</span><span class="bu">range</span>(<span class="bu">len</span>(month_labels)), labels<span class="op">=</span>month_labels, rotation<span class="op">=</span><span class="dv">80</span>, ha<span class="op">=</span><span class="st">'right'</span>)</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Time Series Heatmap of Sales (Aggregated by Month)'</span>)</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Month and Year'</span>)</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-15-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>
Judging from consitency in the shades of the heatmap, we can see that the demand for the top-selling product is fairly stable over time. However, it is interesting to note that the amount of sales recorded for first quarters of <code>2015</code>, <code>2016</code> and <code>2017</code> remained consistent however in 2018 the amount of sales recorded in the first quarter dipped significantly. This is an interesting insight that we can explore further.
</p>
<p>
Next, I will use the <code>Prophet</code> library to model the demand for the top-selling product. This will help us understand the cyclical patterns in the demand for the top-selling product
</p>
<h4 class="anchored">
Forecasting Demand of the Top-selling Product with Prophet
</h4>
<p>
Prophet is a forecasting tool developed by Facebook. It is designed for analyzing time series data that display patterns on different time scales such as yearly, weekly, and daily. It also has advanced capabilities for modeling the effects of holidays on a time-series and implementing custom seasonalities. see the documentation <a href="#">here</a>
</p>
<div class="cell" data-execution_count="28">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import prophet</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> prophet <span class="im">import</span> Prophet</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>prophet_df <span class="op">=</span> df.copy()</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>prophet_df <span class="op">=</span> prophet_df.rename(columns<span class="op">=</span>{<span class="st">'shipping date (DateOrders)'</span>: <span class="st">'ds'</span>, <span class="st">'Sales'</span>: <span class="st">'y'</span>})</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Add custom Puerto Rico holidays</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the CSV file</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>holidays_df <span class="op">=</span> pd.read_csv(<span class="st">'data/puertorican_holidays.csv'</span>)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename the 'Date' column to 'ds' and the 'Name' column to 'holiday'</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>holidays_df <span class="op">=</span> holidays_df.rename(columns<span class="op">=</span>{<span class="st">'Date'</span>: <span class="st">'ds'</span>, <span class="st">'Name'</span>: <span class="st">'holiday'</span>})</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop the 'Type' column as it's not needed</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>holidays_df <span class="op">=</span> holidays_df.drop(columns<span class="op">=</span>[<span class="st">'Type'</span>])</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Add 'lower_window' and 'upper_window' columns</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>holidays_df[<span class="st">'lower_window'</span>] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>holidays_df[<span class="st">'upper_window'</span>] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert 'ds' to datetime</span></span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>holidays_df[<span class="st">'ds'</span>] <span class="op">=</span> pd.to_datetime(holidays_df[<span class="st">'ds'</span>])</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a Prophet instance and provide the holidays DataFrame</span></span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>prophet <span class="op">=</span> Prophet(holidays<span class="op">=</span>holidays_df)</span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>prophet.fit(prophet_df)</span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a DataFrame with future dates for forecasting</span></span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a>future <span class="op">=</span> prophet.make_future_dataframe(periods<span class="op">=</span><span class="dv">365</span>, freq<span class="op">=</span><span class="st">'D'</span>)</span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate forecasts</span></span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a>forecast <span class="op">=</span> prophet.predict(future) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>08:16:49 - cmdstanpy - INFO - Chain [1] start processing
08:42:00 - cmdstanpy - INFO - Chain [1] done processing</code></pre>
</div>
</div>
<p>
The code above uses the <code>Prophet</code> library to model the demand for the top-selling product. The model is trained on the <code>Sales</code> and <code>Shipping Date</code> columns. The model is then used to forecast the demand for the top-selling product over the next 365 days.
</p>
<p>
The code also included Puerto Rican holidays to account for the impact of holidays on the demand for the top-selling product. This is important because holidays can have a significant impact on demand patterns.
</p>
<p>
You might wonder why Puerto Rican holidays were included in the model. From the univariate analysis conducted earlier, we discovered that most of the orders were coming from Puerto Rico. The <code>forecast</code> variable now contains the forecasted values for the top-selling product. we will work with the variable later but for now, let’s evaluate the accuracy of our prophet model
</p>
<h4 class="anchored">
Evaluating the Accuracy of the Time Series Forecast
</h4>
<p>
To determine the accuracy of the prophet model, we will use the <code>cross_validationa()</code> function provided by <code>Prophet</code>
</p>
<div class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> prophet.diagnostics <span class="im">import</span> cross_validation, performance_metrics</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform cross-validation</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform cross-validation</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>df_cv <span class="op">=</span> cross_validation(model<span class="op">=</span>prophet, initial<span class="op">=</span><span class="st">'730 days'</span>, period<span class="op">=</span><span class="st">'365 days'</span>, horizon<span class="op">=</span><span class="st">'365 days'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<script type="application/vnd.jupyter.widget-view+json">
{"model_id":"3b362dfb425f4057a2668c13fbafe3f5","version_major":2,"version_minor":0,"quarto_mimetype":"application/vnd.jupyter.widget-view+json"}
</script>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>08:41:21 - cmdstanpy - INFO - Chain [1] start processing
08:46:10 - cmdstanpy - INFO - Chain [1] done processing</code></pre>
</div>
</div>
<p>
The <code>cross_validation()</code> function performs cross-validation on the model. It trains the model on a subset of the data and then evaluates the model on the remaining data. This is a good way to evaluate the accuracy of the model. The <code>initial</code> parameter specifies the size of the training set. The <code>period</code> parameter specifies the frequency of the forecast.
</p>
<p>
Let’s visualize the performance of the model
</p>
<div class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot MAPE</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> prophet.plot <span class="im">import</span> plot_cross_validation_metric</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plot_cross_validation_metric(df_cv, metric<span class="op">=</span><span class="st">'mape'</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>fig.get_axes()[<span class="dv">0</span>].get_lines()[<span class="dv">0</span>].set_markerfacecolor(<span class="st">'#ADD8E7'</span>)  <span class="co"># Change color of the dots</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>fig.get_axes()[<span class="dv">0</span>].get_lines()[<span class="dv">0</span>].set_markeredgecolor(<span class="st">'#ADD8E7'</span>)  <span class="co"># Change color of the dot edges</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-18-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>
The forecast has lower MAPE (Mean Absolute Percentage Error) values for horizons within the 200-day range however the accuracy drops for horizons beyond 250 days. This suggests that the model is making more errors at periods beyond 250 days.
</p>
<p>
The model will be most useful to stakeholders if it can forecast demand beyond 250 days with a lower percentage of errors. Exposing the model to more historical data may help lower the MAPE significantly. nonetheless, let’s explore if there are opportunities to improve the accuracy by finding the best combinations of hyperparameters for the prophet model. I will use a <a href="#">hyperparameter tuning</a> technique to try to optimize the model’s performance.
</p>
<h4 class="anchored">
Finding the Best Hyperparameter Combination for Lower MAPE
</h4>
<div class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> ParameterGrid</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming prophet_df is your DataFrame with 'ds' and 'y' columns</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>prophet_df <span class="op">=</span> df.copy()</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>prophet_df <span class="op">=</span> prophet_df.rename(columns<span class="op">=</span>{<span class="st">'shipping date (DateOrders)'</span>: <span class="st">'ds'</span>, <span class="st">'Sales'</span>: <span class="st">'y'</span>})</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify hyperparameter values to try</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>param_grid <span class="op">=</span> {</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'seasonality_mode'</span>: [<span class="st">"additive"</span>, <span class="st">'multiplicative'</span>],</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'seasonality_prior_scale'</span>: [<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">20</span>],</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'holidays_prior_scale'</span>: [<span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">25</span>],</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'changepoint_prior_scale'</span>: [<span class="fl">0.005</span>, <span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="fl">0.1</span>]</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate all combinations of hyperparameters using ParameterGrid</span></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>param_combinations <span class="op">=</span> ParameterGrid(param_grid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>
The code above uses the <code>ParameterGrid</code> function from the <code>sklearn</code> library to create a grid of hyperparameters. The grid contains different combinations of hyperparameters for the prophet model.
</p><p>
The code below then uses the <code>cross_validation()</code> function to evaluate the accuracy of the model for each combination of hyperparameters. The code then selects the combination of hyperparameters that results in the lowest MAPE.
</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> itertools <span class="im">import</span> product</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Store results in a dictionary</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> {}</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"trying all </span><span class="sc">{</span><span class="bu">len</span>(param_combinations)<span class="sc">}</span><span class="ss"> hyperparameter combinations"</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate all combinations of hyperparameters</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>param_combinations <span class="op">=</span> <span class="bu">list</span>(product(<span class="op">*</span>param_grid.values()))</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> params <span class="kw">in</span> param_combinations:</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create a Prophet instance with current hyperparameter values</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>    prophet <span class="op">=</span> Prophet(<span class="op">**</span><span class="bu">dict</span>(<span class="bu">zip</span>(param_grid.keys(), params)))</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Fit the model</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>    prophet.fit(prophet_df)</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Perform cross-validation</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>    df_cv <span class="op">=</span> cross_validation(model<span class="op">=</span>prophet, initial<span class="op">=</span><span class="st">'730 days'</span>, period<span class="op">=</span><span class="st">'365 days'</span>, horizon<span class="op">=</span><span class="st">'365 days'</span>)</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate performance metrics</span></span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>    df_metrics <span class="op">=</span> performance_metrics(df_cv, rolling_window<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Store metrics in the results dictionary</span></span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>    results[params] <span class="op">=</span> df_metrics[<span class="st">'mape'</span>].mean()</span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>:::: {.callout .note} <strong>Note:</strong> The code took a very long time to complete. It tried 128 different combinations of hyperparameters and the best model was the one with the lowest MAPE value. The best model had the following hyperparameters:</p>
<p>::::</p>
<p>
The results are in! The best model had the following hyperparameters:
</p>
<div class="cell" data-execution_count="53">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the hyperparameters with the lowest RMSE</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>best_hyperparams <span class="op">=</span> <span class="bu">min</span>(results, key<span class="op">=</span>results.get)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Best Hyperparameters: </span><span class="sc">{</span><span class="bu">dict</span>(<span class="bu">zip</span>(param_grid.keys(), best_hyperparams))<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Best Hyperparameters: {'seasonality_mode': 'additive', 'seasonality_prior_scale': 1, 'holidays_prior_scale': 5, 'changepoint_prior_scale': 0.005}</code></pre>
</div>
</div>
<p>Now let’s rebuild the model with the best hyperparameters and evaluate the model’s performance.</p>
<div class="cell" data-execution_count="34">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>tuned_prophet <span class="op">=</span> Prophet(holidays<span class="op">=</span>holidays_df, </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>                        seasonality_mode<span class="op">=</span><span class="st">'additive'</span>, </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>                        seasonality_prior_scale<span class="op">=</span><span class="dv">1</span>, </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>                        holidays_prior_scale<span class="op">=</span><span class="dv">5</span>, </span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>                        changepoint_prior_scale<span class="op">=</span><span class="fl">0.005</span>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="co"># fit the model</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>tuned_prophet.fit(prophet_df)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a DataFrame with future dates for forecasting</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>future <span class="op">=</span> tuned_prophet.make_future_dataframe(periods<span class="op">=</span><span class="dv">365</span>, freq<span class="op">=</span><span class="st">'D'</span>)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate forecasts</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>new_forecast <span class="op">=</span> tuned_prophet.predict(future)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>09:06:40 - cmdstanpy - INFO - Chain [1] start processing
09:19:32 - cmdstanpy - INFO - Chain [1] done processing</code></pre>
</div>
</div>
<p>cross validate tuned model</p>
<div class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> prophet.diagnostics <span class="im">import</span> cross_validation, performance_metrics</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform cross-validation</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>tuned_df_cv <span class="op">=</span> cross_validation(model<span class="op">=</span>tuned_prophet, initial<span class="op">=</span><span class="st">'730 days'</span>, period<span class="op">=</span><span class="st">'365 days'</span>, horizon<span class="op">=</span><span class="st">'365 days'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<script type="application/vnd.jupyter.widget-view+json">
{"model_id":"8a40355bb29643119ddeea42a69c97ad","version_major":2,"version_minor":0,"quarto_mimetype":"application/vnd.jupyter.widget-view+json"}
</script>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>09:23:58 - cmdstanpy - INFO - Chain [1] start processing
09:26:52 - cmdstanpy - INFO - Chain [1] done processing</code></pre>
</div>
</div>
<p>let’s compare the accuracy of the model before and after hyperparameter tuning. Drumroll please!</p>
<div class="cell" data-execution_count="66">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>fig, axs <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">5</span>))</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the first cross-validation metric</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>fig1 <span class="op">=</span> plot_cross_validation_metric(df_cv, metric<span class="op">=</span><span class="st">'mape'</span>, ax<span class="op">=</span>axs[<span class="dv">0</span>])</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>fig1.get_axes()[<span class="dv">0</span>].get_lines()[<span class="dv">0</span>].set_markerfacecolor(<span class="st">'#ADD8E7'</span>)  <span class="co"># Change color of the dots</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>fig1.get_axes()[<span class="dv">0</span>].get_lines()[<span class="dv">0</span>].set_markeredgecolor(<span class="st">'#ADD8E7'</span>)  <span class="co"># Change color of the dot edges</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="co"># add title</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">0</span>].set_title(<span class="st">'Initial Cross-Validation score MAPE'</span>)</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the second cross-validation metric</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>fig2 <span class="op">=</span> plot_cross_validation_metric(tuned_df_cv, metric<span class="op">=</span><span class="st">'mape'</span>, ax<span class="op">=</span>axs[<span class="dv">1</span>])</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>fig2.get_axes()[<span class="dv">0</span>].get_lines()[<span class="dv">0</span>].set_markerfacecolor(<span class="st">'#ADD8E7'</span>)  <span class="co"># Change color of the dots</span></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>fig2.get_axes()[<span class="dv">0</span>].get_lines()[<span class="dv">0</span>].set_markeredgecolor(<span class="st">'#ADD8E9'</span>)  <span class="co"># Change color of the dot edges</span></span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a><span class="co"># add title</span></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">1</span>].set_title(<span class="st">'Tuned Cross-Validation score MAPE'</span>)</span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-24-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>
Not Exactly the outcome I was expecting but the tuned model’s performance remains consistent with the previous model. This is may suggest that the model is not sensitive to the hyperparameters. Nonetheless, the model is still useful for forecasting demand for the top-selling product.
</p>
<h4 class="anchored">
Forecast Results
</h4>
<p>As indicated earlier, the <code>forecast</code> variable contains the forecasted values of our <code>Sales</code> time series. Based on this forecast we will calculate the optimal inventory policy for this specific product.</p>
<p>
The <code>forecast</code> variable is a dataframe that contains the following columns:
</p>
<div class="cell" data-execution_count="67">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>forecast.head(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="67">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ds</th>
<th data-quarto-table-cell-role="th">trend</th>
<th data-quarto-table-cell-role="th">yhat_lower</th>
<th data-quarto-table-cell-role="th">yhat_upper</th>
<th data-quarto-table-cell-role="th">trend_lower</th>
<th data-quarto-table-cell-role="th">trend_upper</th>
<th data-quarto-table-cell-role="th">American Citizenship Day</th>
<th data-quarto-table-cell-role="th">American Citizenship Day_lower</th>
<th data-quarto-table-cell-role="th">American Citizenship Day_upper</th>
<th data-quarto-table-cell-role="th">Christmas Day</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">weekly</th>
<th data-quarto-table-cell-role="th">weekly_lower</th>
<th data-quarto-table-cell-role="th">weekly_upper</th>
<th data-quarto-table-cell-role="th">yearly</th>
<th data-quarto-table-cell-role="th">yearly_lower</th>
<th data-quarto-table-cell-role="th">yearly_upper</th>
<th data-quarto-table-cell-role="th">multiplicative_terms</th>
<th data-quarto-table-cell-role="th">multiplicative_terms_lower</th>
<th data-quarto-table-cell-role="th">multiplicative_terms_upper</th>
<th data-quarto-table-cell-role="th">yhat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2015-01-03 00:00:00</td>
<td>189.503452</td>
<td>61.858391</td>
<td>396.408660</td>
<td>189.503452</td>
<td>189.503452</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>...</td>
<td>-1.288207</td>
<td>-1.288207</td>
<td>-1.288207</td>
<td>33.801001</td>
<td>33.801001</td>
<td>33.801001</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>220.974183</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2015-01-03 03:30:00</td>
<td>189.646216</td>
<td>57.050118</td>
<td>384.288236</td>
<td>189.646216</td>
<td>189.646216</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>...</td>
<td>-1.373629</td>
<td>-1.373629</td>
<td>-1.373629</td>
<td>33.618634</td>
<td>33.618634</td>
<td>33.618634</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>221.460580</td>
</tr>
</tbody>
</table>

<p>2 rows × 73 columns</p>
</div>
</div>
</div>
<p>
Before calculating the optimal inventory policy, let’s visualize the forecasted sales data. To have a feel for the seasonalities and cycles in the forecasted sales data
</p>
<h4 class="anchored">
Visualizing Forecasted Sales
</h4>
<div class="cell" data-execution_count="69">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Ignore the specific FutureWarning</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>, category<span class="op">=</span><span class="pp">FutureWarning</span>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the forecast</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>tuned_prophet.plot_components(new_forecast)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="69">
<p><img src="index_files/figure-html/cell-26-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-26-output-2.png" class="img-fluid"></p>
</div>
</div>
<h4 class="anchored">
Forecast Observations
</h4>
<p>
The sales trend between <code>2015</code> and <code>2017</code> marks a cycle where sales for the product remained relatively stable during the second and third quarters of each year and then dipped slightly in October with a sharp increase between November and December.
</p>
<p>
The zero variance observed in the product price may account for the relatively stable sales pattern forecasted for 2018 and 2019. It might also be worth investigating the factors that may account for the cyclical dips between 2015 and 2017
</p>
<p>
We can also observe the impact of the Puerto Rican holidays on the forecasted sales.
</p>
<h2 class="anchored">
Optimizing Inventory Policy Based on Forecasted Demand
</h2>
<p>
Now that we have forecasted the demand for the top-selling product, we can use the forecasted demand to calculate the optimal inventory policy for the product. The optimal inventory policy will help us determine the reorder point, safety stock, and economic order quantity for the product. This will help us ensure that we have the right amount of inventory on hand to meet customer demand while minimizing inventory costs.
</p>
<h3 class="anchored">
Bivariate Analysis Using Heat Maps
</h3>
<p>My goal for this step was to understand the relationship between each variable and the <code>Sales</code>.</p>
<p>
Considering that there are many variables, I decided to use heatmaps to visualize the correlation coefficients between each variable and the target variable because it allowed me to visualize the correlation between each variable and the target variable in one plot. This is a very efficient way to visualize the correlation between variables.
</p>
<p>
We need to remove the <code>Sales per customer</code> column from the dataset because it introduces <a href="#">collinearity</a> in the correlation matrix. The <code>Sale per customer</code> is similar to the <code>Sales</code> column.
</p>
<p>
</p><p>Collinearity is a statistical phenomenon in which two or more predictor variables in a multiple regression model are highly correlated, meaning that one can be linearly predicted from the others with a substantial degree of accuracy. This affects our ability to interpret the model results more accurately. &lt;/p.</p>
<div class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>label_encode_df.drop(columns<span class="op">=</span>[<span class="st">'Sales per customer'</span>], inplace<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform bivariate analysis using heatmap</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">8</span>))</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>sns.heatmap(label_encode_df.corr(), annot<span class="op">=</span><span class="va">True</span>, cmap<span class="op">=</span><span class="st">'coolwarm'</span>)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Correlation Matrix of the Dataset'</span>)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the plot</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-30-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>
From the heatmap, we can see that the variables have a weak linear relationship with the target variable(<code>Sales</code>)
</p>
<p>
We will use Machine Learning models to capture more complex relationships between the variables and the target variable
</p>
<h2 class="anchored">
Demand Prediction With Machine Learning Using Linear Regressor and Random Forest Models
</h2>
<p>
To build a predictive model to predict sales outcome I used the <a href="https://www.ibm.com/topics/random-forest#:~:text=Random%20forest%20is%20a%20commonly,both%20classification%20and%20regression%20problems.">Random Forest</a> algorithm and <a href=""> Linear Regressor Model.</a>
</p>
<p>
The Random Forest algorithm was chosen because apart from being a powerful and robust algorithm, it is also an ensemble learning method for classification and regression. It works by constructing a multitude of decision trees at training time and outputs the class that is the mode of the classes or mean prediction of the individual trees. It is a supervised learning algorithm that is used for both classification and regression problems.
</p>
<p>
The Linear Regressor Model, on the other hand, was chosen because it is a learning algorithm that is based on the idea that there exists a linear relationship between the dependent variable and the independent variables. It is a supervised learning algorithm that is used to predict real-valued output. It works by fitting a linear equation to the observed data.
</p>
<p>
The two models will be trained on the same dataset and their performance will be compared to determine the best model for the task.
</p>
<p>Before model fitting let’s confirm that the categorical variables have been successfully one-hot encoded.</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>onehot_encode_df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Days for shipping (real)</th>
<th data-quarto-table-cell-role="th">Sales per customer</th>
<th data-quarto-table-cell-role="th">Late_delivery_risk</th>
<th data-quarto-table-cell-role="th">Sales</th>
<th data-quarto-table-cell-role="th">Shipping Year</th>
<th data-quarto-table-cell-role="th">Shipping Month</th>
<th data-quarto-table-cell-role="th">Shipping Day</th>
<th data-quarto-table-cell-role="th">Shipping Weekday</th>
<th data-quarto-table-cell-role="th">Type_CASH</th>
<th data-quarto-table-cell-role="th">Type_DEBIT</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">Customer City_Zanesville</th>
<th data-quarto-table-cell-role="th">Market_Africa</th>
<th data-quarto-table-cell-role="th">Market_Europe</th>
<th data-quarto-table-cell-role="th">Market_LATAM</th>
<th data-quarto-table-cell-role="th">Market_Pacific Asia</th>
<th data-quarto-table-cell-role="th">Market_USCA</th>
<th data-quarto-table-cell-role="th">Shipping Mode_First Class</th>
<th data-quarto-table-cell-role="th">Shipping Mode_Same Day</th>
<th data-quarto-table-cell-role="th">Shipping Mode_Second Class</th>
<th data-quarto-table-cell-role="th">Shipping Mode_Standard Class</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">48</td>
<td>5</td>
<td>115.180000</td>
<td>1</td>
<td>119.980003</td>
<td>2016</td>
<td>2</td>
<td>29</td>
<td>0</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">57</td>
<td>6</td>
<td>117.580002</td>
<td>1</td>
<td>119.980003</td>
<td>2016</td>
<td>4</td>
<td>19</td>
<td>1</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">58</td>
<td>4</td>
<td>95.980003</td>
<td>1</td>
<td>119.980003</td>
<td>2016</td>
<td>5</td>
<td>26</td>
<td>3</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">66</td>
<td>4</td>
<td>176.369995</td>
<td>1</td>
<td>179.970001</td>
<td>2015</td>
<td>9</td>
<td>26</td>
<td>5</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">67</td>
<td>2</td>
<td>167.369995</td>
<td>0</td>
<td>179.970001</td>
<td>2017</td>
<td>7</td>
<td>4</td>
<td>1</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
</tbody>
</table>

<p>5 rows × 590 columns</p>
</div>
</div>
</div>
<h3 class="anchored">
Split Data for Training and Testing
</h3>
<p>
The next step is to split the data into training and testing datasets. I used the <code>train_test_split()</code> method from the <code>sklearn.model_selection</code> module to split the data into training and testing datasets. Doing so will allow me to train the model on the training dataset and test the model on the testing dataset.
</p>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> onehot_encode_df.drop(<span class="st">'Sales'</span>, axis<span class="op">=</span><span class="dv">1</span>)  <span class="co"># exclude the target variable)</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> onehot_encode_df[<span class="st">'Sales'</span>]  <span class="co"># Target variable</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Split the dataset into trainig and testing sets</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>    X, y, test_size<span class="op">=</span><span class="fl">0.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>X</code>: the features to be used for training the model. In this case, the features are all the columns in the dataset except the target variable <code>Sales</code>.</p>
<p><code>y</code>: the target variable to be predicted. In this case, the target variable is <code>Sales</code>.</p>
<p><code>X_train</code>: the features to be used for training the models.</p>
<p><code>X_test</code>: the features to be used for testing the models on unseen data.</p>
<p><code>y_train</code>: the target variable to be used for training the model.</p>
<p><code>y_test</code>: the target variable to be used for testing the model.</p>
<h3 class="anchored">
Training the Model
</h3>
<p>
Now that the data has been successfully preprocessed, I can proceed to train the model. I used the <code>RandomForestRegressor()</code> class from the <code>sklearn.ensemble</code> module to train the model. The <code>RandomForestClassifier()</code> method takes the following arguments:
</p>
<ul>
<li>
<code>n_estimators</code>: the number of trees in the forest. I set this to 200.
</li>
<li>
<code>max_depth</code>: the maximum depth of the tree. I set this to 15.
</li>
<li>
<code>random_state</code>: the seed used by the random number generator. I set this to 42.
</li>
</ul>
<h4 class="anchored">
Random Forest Algorithm
</h4>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestRegressor</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>n_estimators <span class="op">=</span> <span class="dv">200</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>max_depth <span class="op">=</span> <span class="dv">15</span>  <span class="co"># or a specific value</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the RandomForestClassifier instance</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>rf_model <span class="op">=</span> RandomForestRegressor(</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>    n_estimators<span class="op">=</span>n_estimators,</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>    max_depth<span class="op">=</span>max_depth,</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>    random_state<span class="op">=</span><span class="dv">42</span>  <span class="co"># You can set a random state for reproducibility</span></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model to the training data</span></span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>rf_model.fit(X_train, y_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<style>#sk-container-id-1 {color: black;}#sk-container-id-1 pre{padding: 0;}#sk-container-id-1 div.sk-toggleable {background-color: white;}#sk-container-id-1 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-1 label.sk-toggleable__label-arrow:before {content: "▸";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-1 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-1 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-1 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: "▾";}#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-1 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-1 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-1 div.sk-parallel-item::after {content: "";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 div.sk-serial::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-1 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-1 div.sk-item {position: relative;z-index: 1;}#sk-container-id-1 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-1 div.sk-item::before, #sk-container-id-1 div.sk-parallel-item::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-1 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-1 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-1 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-1 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-1 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-1 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-1 div.sk-label-container {text-align: center;}#sk-container-id-1 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-1 div.sk-text-repr-fallback {display: none;}</style><div id="sk-container-id-1" class="sk-top-container"><div class="sk-text-repr-fallback"><pre>RandomForestRegressor(max_depth=15, n_estimators=200, random_state=42)</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br>On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class="sk-container" hidden=""><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-1" type="checkbox" checked=""><label for="sk-estimator-id-1" class="sk-toggleable__label sk-toggleable__label-arrow">RandomForestRegressor</label><div class="sk-toggleable__content"><pre>RandomForestRegressor(max_depth=15, n_estimators=200, random_state=42)</pre></div></div></div></div></div>
</div>
</div>
<h4 class="anchored">
Linear Regression
</h4>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>lr_model <span class="op">=</span> LinearRegression()</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>lr_model.fit(X_train, y_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<style>#sk-container-id-2 {color: black;}#sk-container-id-2 pre{padding: 0;}#sk-container-id-2 div.sk-toggleable {background-color: white;}#sk-container-id-2 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-2 label.sk-toggleable__label-arrow:before {content: "▸";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-2 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-2 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-2 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-2 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-2 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-2 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: "▾";}#sk-container-id-2 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-2 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-2 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-2 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-2 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-2 div.sk-parallel-item::after {content: "";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-2 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-2 div.sk-serial::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-2 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-2 div.sk-item {position: relative;z-index: 1;}#sk-container-id-2 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-2 div.sk-item::before, #sk-container-id-2 div.sk-parallel-item::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-2 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-2 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-2 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-2 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-2 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-2 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-2 div.sk-label-container {text-align: center;}#sk-container-id-2 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-2 div.sk-text-repr-fallback {display: none;}</style><div id="sk-container-id-2" class="sk-top-container"><div class="sk-text-repr-fallback"><pre>LinearRegression()</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br>On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class="sk-container" hidden=""><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-2" type="checkbox" checked=""><label for="sk-estimator-id-2" class="sk-toggleable__label sk-toggleable__label-arrow">LinearRegression</label><div class="sk-toggleable__content"><pre>LinearRegression()</pre></div></div></div></div></div>
</div>
</div>
<h3 class="anchored">
Evaluating the Models
</h3>
<p>
Now that the Linear Regression and Random forest Regressor models have been trained, I can proceed to evaluate each model.
</p>
<p>
I used the <code>Root Mean Squared Error(RSME) Metric</code> to evaluate each model. This metric measures …. the lowest of the two RMSEs indicates the best model to select the value the better.
</p>
<div class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_squared_error</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions on the test set</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>rf_prediction <span class="op">=</span> rf_model.predict(X_test)</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>lr_prediction <span class="op">=</span> lr_model.predict(X_test)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the model</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>rf_mse <span class="op">=</span> mean_squared_error(y_test, rf_prediction)</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>lr_mse <span class="op">=</span> mean_squared_error(y_test, lr_prediction)</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Root Mean Squared Error for Random Forest Regressor: </span><span class="sc">{</span>rf_mse<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Root Mean Squared Error for Linear Regression: </span><span class="sc">{</span>lr_mse<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Root Mean Squared Error for Random Forest Regressor: 43.300144790077574
Root Mean Squared Error for Linear Regression: 246.42162579180308</code></pre>
</div>
</div>
<p>It is clear from the <code>RSME</code> scores that the Random Forest Regressor Model is far more superior for our use case.</p>
<h2 class="anchored">
Accuracy Score
</h2>
<p>
Based on the test results:
</p>
<ul>
<li>
The accuracy is 84.96%, indicating the overall proportion of correct predictions.
</li>
<li>
The precision, recall, and F1-score for class 0 (booking not completed) are relatively high, suggesting good performance in predicting this class.
</li>
<li>
The model struggles with class 1 (booking completed), as indicated by lower precision, recall, and F1-score.
</li>
</ul>
<p>
The class 1 recall is particularly low (0.18), indicating that the model is not capturing a significant portion of actual positive instances. This is a significant issue because the goal is to predict booking completions. The model is not performing well in this regard.
</p>
<p>
The reason for this is the class imbalance, recall that from the univariate analysis the majority of <code>booking_complete</code> is 0 indicating that the majority of customers do not complete the booking. The model is biased towards predicting 0 because of the class imbalance. This is a very important insight because it informs the next steps in the project.
</p>
<h2 class="anchored">
Improving the Model
</h2>
<p>
Now that I have a baseline model, I can proceed to improve the model. I used the following techniques to improve the model:
</p>
<ul class="task-list">
<li><input type="checkbox" checked="">Resolving the class imbalance.</li>
<li><input type="checkbox" checked="">Hyperparameter tuning.</li>
</ul>
<h3 class="anchored">
Resolving the Class Imbalance
</h3>
<p>
I implemented oversampling the class 1(booking complete) using the Synthetic Minority Over-sampling Technique (SMOTE), which is a popular technique for oversampling imbalanced datasets. I used the <code>SMOTE()</code> method from the <code>imblearn.over_sampling</code> module to oversample the minority class.
</p>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply SMOTE to the training set</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> imblearn.over_sampling <span class="im">import</span> SMOTE</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>smote <span class="op">=</span> SMOTE(random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>X_resampled, y_resampled <span class="op">=</span> smote.fit_resample(X_train, y_train)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create and train the RandomForestClassifier on the resampled data</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>rf_model <span class="op">=</span> RandomForestClassifier(n_estimators<span class="op">=</span><span class="dv">100</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>rf_model.fit(X_resampled, y_resampled)</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions on the test set</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> rf_model.predict(X_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.</code></pre>
</div>
</div>
<h2 class="anchored">
Re-Evaluating the Model
</h2>
<p>
Now that the model has been trained with oversampled data, I can proceed to re-evaluate the model. I used the <code>accuracy_score()</code> <code>classification_report()</code> and <code>confusion_matrix()</code> methods to evaluate the model.
</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the model</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> rf_model.predict(X_test)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the model</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>accuracy <span class="op">=</span> accuracy_score(y_test, y_pred)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>report <span class="op">=</span> classification_report(y_test, y_pred)</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>confusion_mat <span class="op">=</span> confusion_matrix(y_test, y_pred)</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Accuracy: </span><span class="sc">{</span>accuracy<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Classification Report:</span><span class="ch">\n</span><span class="st">"</span>, report)</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Confusion Matrix:</span><span class="ch">\n</span><span class="st">"</span>, confusion_mat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy: 0.8373
Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.95      0.91      8504
           1       0.42      0.22      0.28      1496

    accuracy                           0.84     10000
   macro avg       0.64      0.58      0.60     10000
weighted avg       0.80      0.84      0.81     10000

Confusion Matrix:
 [[8050  454]
 [1173  323]]</code></pre>
</div>
</div>
<p>
In the second test (with oversampling):
</p>
<p>
</p><li>
The recall for class 1 has increased from <code>0.16</code> to <code>0.22</code>, indicating an improvement in capturing actual positive instances of booking completions
</li>

<p></p>
<h2 class="anchored">
Improving Overall Accuracy With Hyperparameter Tuning
</h2>
<p>
Now that the model has been trained with oversampled data, I can proceed to improve the model. I used the following techniques to improve the model with hyperparameter Tuning
</p>
<p>
<a href="https://en.wikipedia.org/wiki/Hyperparameter_optimization">Hyperparameter tuning</a> is the process of finding the best combination of hyperparameters for a machine learning algorithm that results in the best performance. Hyperparameters are variables that are set before training a model. They control the learning process and the resulting model.
</p>
<p>
The Random Forest algorithm has several hyperparameters that can be tuned to improve the model’s performance. I used the <code>HalvingGridSearchCV()</code> method from the <code>sklearn.model_selection</code> module to tune the hyperparameters. I opted for the HalvingGridsearch method because it’s relatively faster compared to the traditional GridSearch method
</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.experimental <span class="im">import</span> enable_halving_search_cv  <span class="co"># noqa</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> HalvingGridSearchCV</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the parameter grid to search</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>param_grid <span class="op">=</span> {</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_estimators'</span>: [<span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">150</span>],</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'max_depth'</span>: [<span class="va">None</span>, <span class="dv">10</span>, <span class="dv">20</span>],</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'min_samples_split'</span>: [<span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">10</span>],</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'min_samples_leaf'</span>: [<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">4</span>],</span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'max_features'</span>: [<span class="st">'sqrt'</span>, <span class="st">'log2'</span>]</span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a RandomForestClassifier</span></span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>rf_model <span class="op">=</span> RandomForestClassifier(random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Create HalvingGridSearchCV object</span></span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a>halving_search <span class="op">=</span> HalvingGridSearchCV(</span>
<span id="cb51-18"><a href="#cb51-18" aria-hidden="true" tabindex="-1"></a>    estimator<span class="op">=</span>rf_model, param_grid<span class="op">=</span>param_grid, cv<span class="op">=</span><span class="dv">5</span>, scoring<span class="op">=</span><span class="st">'accuracy'</span>, factor<span class="op">=</span><span class="dv">3</span></span>
<span id="cb51-19"><a href="#cb51-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb51-20"><a href="#cb51-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-21"><a href="#cb51-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model to the data</span></span>
<span id="cb51-22"><a href="#cb51-22" aria-hidden="true" tabindex="-1"></a>halving_search.fit(X_resampled, y_resampled)</span>
<span id="cb51-23"><a href="#cb51-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-24"><a href="#cb51-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the best parameters</span></span>
<span id="cb51-25"><a href="#cb51-25" aria-hidden="true" tabindex="-1"></a>best_params <span class="op">=</span> halving_search.best_params_</span>
<span id="cb51-26"><a href="#cb51-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Best Hyperparameters:"</span>, best_params)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Best Hyperparameters: {'max_depth': None, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 100}</code></pre>
</div>
</div>
<h3 class="anchored">
Results From The Hyperparameter Tuning Process:
</h3>
<p>
The best combination of hyperparameters is:
</p>
<ul>
<li>
<code>max_depth</code> = None
</li>
<li>
<code>max_features</code> = sqrt
</li>
<li>
<code>min_samples_leaf</code> = 1
</li>
<li>
<code>min_samples_split</code> = 2
</li>
<li>
<code>n_estimators</code> = 100
</li>
</ul>
<h2 class="anchored">
Re-fitting the Model With the Best Parameters
</h2>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply SMOTE to the training set</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> imblearn.over_sampling <span class="im">import</span> SMOTE</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>smote <span class="op">=</span> SMOTE(random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>X_resampled, y_resampled <span class="op">=</span> smote.fit_resample(X_train, y_train)</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create and train the RandomForestClassifier on the resampled data</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>rf_model <span class="op">=</span> RandomForestClassifier(max_depth<span class="op">=</span><span class="va">None</span>, </span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>                                  max_features<span class="op">=</span><span class="st">'sqrt'</span>,</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>                                  min_samples_leaf<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>                                  min_samples_split<span class="op">=</span><span class="dv">2</span>, </span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>                                  n_estimators<span class="op">=</span><span class="dv">100</span>, </span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>                                  random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a>rf_model.fit(X_resampled, y_resampled)</span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions on the test set</span></span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> rf_model.predict(X_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<h2 class="anchored">
Re-Evaluating the Model
</h2>
<p>
Now that the model has been trained with the best parameters, I can proceed to re-evaluate the model. like before, I tested the accuracy, and confusion matrix and created a report
</p>
<p>
I also further tested with AUROC metric to check the performance of the model given the heavy class imbalance observed
</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the model</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> rf_model.predict(X_test)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the model</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>accuracy <span class="op">=</span> accuracy_score(y_test, y_pred)</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>report <span class="op">=</span> classification_report(y_test, y_pred)</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>confusion_mat <span class="op">=</span> confusion_matrix(y_test, y_pred)</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Accuracy: </span><span class="sc">{</span>accuracy<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Classification Report:</span><span class="ch">\n</span><span class="st">"</span>, report)</span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Confusion Matrix:</span><span class="ch">\n</span><span class="st">"</span>, confusion_mat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy: 0.8373
Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.95      0.91      8504
           1       0.42      0.22      0.28      1496

    accuracy                           0.84     10000
   macro avg       0.64      0.58      0.60     10000
weighted avg       0.80      0.84      0.81     10000

Confusion Matrix:
 [[8050  454]
 [1173  323]]</code></pre>
</div>
</div>
<h3 class="anchored">
Testing with AUROC Metric
</h3>
<p>
Considering the class imbalance, I decided to use the AUROC metric to evaluate the model. The AUROC metric is a popular metric for evaluating classification models with imbalanced classes. I used the <code>roc_auc_score()</code> method from the <code>sklearn.metrics</code> module to evaluate the model.
</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> precision_recall_curve, auc</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict probabilities for positive class (class 1)</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>probas_pred <span class="op">=</span> rf_model.predict_proba(X_test)[:, <span class="dv">1</span>]</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute precision-recall curve and AUC-PR</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>precision, recall, _ <span class="op">=</span> precision_recall_curve(y_test, probas_pred)</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>area_under_pr_curve <span class="op">=</span> auc(recall, precision)</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot Precision-Recall curve</span></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">8</span>))</span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a>plt.plot(recall, precision, label<span class="op">=</span><span class="ss">f'AUC-PR = </span><span class="sc">{</span>area_under_pr_curve<span class="sc">:.2f}</span><span class="ss">'</span>, color<span class="op">=</span><span class="st">'blue'</span>)</span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Recall'</span>)</span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Precision'</span>)</span>
<span id="cb56-15"><a href="#cb56-15" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Precision-Recall Curve'</span>)</span>
<span id="cb56-16"><a href="#cb56-16" aria-hidden="true" tabindex="-1"></a>plt.legend(loc<span class="op">=</span><span class="st">'best'</span>)</span>
<span id="cb56-17"><a href="#cb56-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb56-18"><a href="#cb56-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-19"><a href="#cb56-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Area Under the Precision-Recall Curve (AUC-PR): </span><span class="sc">{</span>area_under_pr_curve<span class="sc">:.2f}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-42-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Area Under the Precision-Recall Curve (AUC-PR): 0.37</code></pre>
</div>
</div>
<h1>
Answering The Business Question With The Predictive Model
</h1>
<p>
Now that I have a predictive model tuned and tested, I can proceed to answer the business question.
</p>
<p>
The Goal of the project is to help British Airwyays understand their customer’s booking behaviour for the holidays by looking at 5000 records of customer fligt booking data. Through the predictive model, we can answer the following business questions:
</p>
<blockquote style="
    font-size: 18px; 
    color: #333; 
    padding: 20px; 
    margin: 20px 0; 
    border-left: 10px solid #7792f9; 
    line-height: 1.6; 
    position: relative; 
    background: #e9f5ff;" class="blockquote">
<em><em style="font-weight:bold">1. </em>What Variables Contribute to Customers Booking Holidays With British Airways</em>
</blockquote>
<blockquote style="
    font-size: 18px; 
    color: #333; 
    padding: 20px; 
    margin: 20px 0; 
    border-left: 10px solid #7792f9; 
    line-height: 1.6; 
    position: relative; 
    background: #e9f5ff;" class="blockquote">
<em><em style="font-weight:bold">2. </em>Is It Viable To Use The Data to Predict Customers Booking Holidays With British Airways</em>
</blockquote>
<p>
Based on the predictive model, we can find out about the variables that have the most significant impact on booking completions
</p>
<h2 class="anchored">
Finding The Most Important Variables
</h2>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract feature importances from the trained model</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>feature_importances <span class="op">=</span> rf_model.feature_importances_</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a DataFrame with feature names and their importance</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>feature_importance_df <span class="op">=</span> pd.DataFrame({<span class="st">'Feature'</span>: X_train.columns, <span class="st">'Importance'</span>: feature_importances})</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort the data frame by importance in descending order</span></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>feature_importance_df <span class="op">=</span> feature_importance_df.sort_values(by<span class="op">=</span><span class="st">'Importance'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Select the top 10 features</span></span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>top_10_features <span class="op">=</span> feature_importance_df.head(<span class="dv">10</span>)</span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the feature importances for the top 10 features</span></span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">8</span>))</span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a>plt.barh(top_10_features[<span class="st">'Feature'</span>], top_10_features[<span class="st">'Importance'</span>])</span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Importance'</span>)</span>
<span id="cb58-17"><a href="#cb58-17" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Top 10 Feature Importances'</span>)</span>
<span id="cb58-18"><a href="#cb58-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb58-19"><a href="#cb58-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-20"><a href="#cb58-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the sorted feature importances for the top 10 features</span></span>
<span id="cb58-21"><a href="#cb58-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(top_10_features)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-43-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                     Feature  Importance
62   booking_origin_Malaysia    0.104948
8            flight_duration    0.085819
1              purchase_lead    0.082578
2             length_of_stay    0.066818
3                flight_hour    0.064356
4                 flight_day    0.050064
15  booking_origin_Australia    0.024203
48  booking_origin_Indonesia    0.023563
0             num_passengers    0.023013
28      booking_origin_China    0.018264</code></pre>
</div>
</div>
<p>
It can be seen from the above plot the top ten(10) most important variables that contribute to customers booking holidays with British Airways
</p>
<h2 class="anchored">
Viability for Use in Making Predictions
</h2>
<p>The model was trained on 5000 records of customer flight booking data. The model was tested on 5000 records of customer flight booking data. The model was able to predict booking completions with 83.7% Accuracy.</p>
<p>However, The model has room for improvement. More data can be collected, particularly data on the customers who completed the booking. This will help to improve the model’s performance significantly. Other techniques include the ensemble approach to learning, which involves combining multiple models to improve the model’s performance.</p>
<p>overall the model is viable for use in making predictions.</p>
<h1>
Conclusion
</h1>
<p>
In this notebook, I demonstrated my data science process for building a predictive model based on customer flight booking data. I performed exploratory data analysis, cleaned and prepared the data for modeling, performed feature engineering, built and evaluated models, tested the model on unseen data, and interpreted the model results to answer the business questions.
</p>
<p>
Through the predictive model, we can answer the following business questions:
</p>
<ul>
<li>
What Variables Contribute to Customers Booking Holidays With British Airways?
</li>
<li>
Is It Viable To Use The Data to Predict Customers Booking Holidays With British Airways?
</li>
</ul>
<p>
With insights from the predictive model, British Airways’ sales and marketing function can deploy their strategy to <code>flight origins</code> like Malaysia, Australia, Indonesia and China to increase their sales and revenue. They can also experiment with promotional incentives around <code>flight duration</code>, <code>purchase lead</code> and <code>length of stay</code>.
</p>
<p>
Logistics and Supply Chain function can use the predictive model to forecast the demand for flights during holiday seasons based on historical booking patterns. This can enable the team to Adjust inventory levels and allocate resources more efficiently in response to predicted demand.
</p>
<p>
If you made it this far, Thank you for reading this notebook. I hope you found it insightful. Please feel free to reach out with comments and feedback on my process.(simontagbor360@gmail.com)
</p>
<div class="column-page">
<h1>
Up Next:
</h1>
</div>
<div class="column-page">
<div style="margin: 0; font-family: Arial, sans-serif; display: flex; justify-content: space-between; padding: 20px;">
<a href="https://simontagbor.github.io/BritishAirways-data-science/" style="text-decoration: none; color: black;">
<div style="width: 300px; border-radius: 15px; overflow: hidden; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); transition: transform 0.3s;">
<img src="assets/blogpngBA.png" alt="Blog Post Image" style="width: 100%; height: auto; border-radius: 15px 15px 0 0;">
<div style="padding: 15px;">
<div style="font-size: 1.2em; font-weight: bold; margin-bottom: 10px;">
Understanding How Customers Feel About British Airways Flight Experience.
</div>
<div style="font-size: 0.9em; color: #555;">
A Topic Modelling and Sentiment Analysis Approach
</div>
</div>
</div>
</a> <a href="#" style="text-decoration: none; color: black;">
<div style="width: 300px; border-radius: 15px; overflow: hidden; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); transition: transform 0.3s;">
<img src="assets/supply.jpg" alt="Blog Post Image" style="width: 100%; height: auto; border-radius: 15px 15px 0 0;">
<div style="padding: 15px;">
<div style="font-size: 1.2em; font-weight: bold; margin-bottom: 10px;">
Supply Chain Demand Forecasting Using Prohet
</div>
<div style="font-size: 0.9em; color: #555;">
Using Prophet Algorithm to Implement a Demand Forecasting Model with Python(Currently A Work In Progress)
</div>
</div>
</div>
</a> <a href="#" style="text-decoration: none; color: black;">
<div style="width: 300px; border-radius: 15px; margin-right:15px; overflow: hidden; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); transition: transform 0.3s;">
<img src="assets/inventory.jpg" alt="Blog Post Image" style="width: 100%; height: auto; border-radius: 15px 15px 0 0;">
<div style="padding: 15px;">
<div style="font-size: 1.2em; font-weight: bold; margin-bottom: 10px;">
Inventory Optimisation With ARIMA and SARIMA
</div>
<div style="font-size: 0.9em; color: #555;">
Using Time Series Analysis to forecast the future demand of a given product.(Work in Progress)
</div>
</div>
</div>
</a><p><a href="#" style="text-decoration: none; color: black;"></a></p>
</div>
</div>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>